# mandatory command for nginx
events {}

# specify all the web trafic
http {
    # specification web server
    server {
        # default internal port for nginx
        listen 80;
        # if the requested address is this one, nginx enters the rule
        server_name vault.astrea;

        location / {
            # name given in docker-compose, resolved by docker
            proxy_pass http://mywebserv:80;
            # transfers the information of the client to the internal web server
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # specification for dozzle
    server{
        listen 80;
        server_name dozzle.astrea;

        location / {
            proxy_pass http://dozzle:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

}