# mandatory command for nginx
events {}

# specify all the web trafic
http {
    # specification web server
    server {
        # default internal port for nginx
        listen 443 ssl;
        # if the requested address is this one, nginx enters the rule
        server_name vault.astrea;
        ssl_certificate /certificates/mywebserv.pem;
        ssl_certificate_key /certificates/mywebserv.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            # name given in docker-compose, resolved by docker
            proxy_pass http://mywebserv:80;
            # transfers the information of the client to the internal web server
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # specification for dozzle
    server{
        listen 443 ssl;
        server_name dozzle.astrea;
        ssl_certificate /certificates/dozzle.pem;
        ssl_certificate_key /certificates/dozzle.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass http://dozzle:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

}

# to generate a certificate : 
# openssl genrsa -out dozzle.key 4096
# openssl req -new -x509 -days 3650 -key dozzle.key -out dozzle.pem -addext "subjectAltName = DNS:dozzle.astrea"
